# Generated by Django 4.1 on 2022-10-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='city',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='country',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='email',
            field=models.EmailField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='phone',
            field=models.CharField(default=True, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='pincode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='state',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
