# Generated by Django 4.1 on 2022-10-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddressbook_city_useraddressbook_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='first_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='last_name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
