# Generated by Django 4.1 on 2022-10-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraddressbook_first_name_useraddressbook_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
